//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestProject1.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //h2[@data-zrqa=&apos;cw-bg2-stitle&apos;].
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@class=&apos;fileuploadInput  &apos;].
        /// </summary>
        internal static string BrowseBtn {
            get {
                return ResourceManager.GetString("BrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-text-component[@cx-prop-label=&apos;Current CTC&apos;].
        /// </summary>
        internal static string CurrentCTC {
            get {
                return ResourceManager.GetString("CurrentCTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-text-component[@cx-prop-label=&apos;Current Employer&apos;].
        /// </summary>
        internal static string CurrentEmployer {
            get {
                return ResourceManager.GetString("CurrentEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //lyte-drop-item[text()=&apos;Fresher&apos;].
        /// </summary>
        internal static string CurrentJobTitle {
            get {
                return ResourceManager.GetString("CurrentJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //lyte-drop-button[@data-zcqa=&apos;manual_Current_Job_Title&apos;].
        /// </summary>
        internal static string CurrentJobTitleDrpDwn {
            get {
                return ResourceManager.GetString("CurrentJobTitleDrpDwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //lyte-icon[@class=&apos;dropdown&apos;].
        /// </summary>
        internal static string DrpDwnFilterJobType {
            get {
                return ResourceManager.GetString("DrpDwnFilterJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-email-component[@cx-prop-label=&apos;Email&apos;].
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-text-component[@cx-prop-label=&apos;Expected CTC&apos;].
        /// </summary>
        internal static string ExpectedCTC {
            get {
                return ResourceManager.GetString("ExpectedCTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //lyte-drop-item[text()=&apos;Engineering&apos;].
        /// </summary>
        internal static string FilterJobCategory {
            get {
                return ResourceManager.GetString("FilterJobCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-text-component[@cx-prop-label=&apos;First Name&apos;].
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;detail-page-applybtn&apos;].
        /// </summary>
        internal static string JobInterest {
            get {
                return ResourceManager.GetString("JobInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[contains(text(),&apos;QA Engineer&apos;)].
        /// </summary>
        internal static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;cw-jobheader-info&apos;].
        /// </summary>
        internal static string JobPageTitle {
            get {
                return ResourceManager.GetString("JobPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-text-component[@cx-prop-label=&apos;Last Name&apos;].
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-website-component[@cx-prop-label=&apos;LinkedIn&apos;].
        /// </summary>
        internal static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-phone-component[@cx-prop-label=&apos;Mobile&apos;].
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-text-component[@cx-prop-label=&apos;Reason for change&apos;].
        /// </summary>
        internal static string ReasonForChange {
            get {
                return ResourceManager.GetString("ReasonForChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //lyte-drop-item[text()=&apos;Ms.&apos;].
        /// </summary>
        internal static string Salutation {
            get {
                return ResourceManager.GetString("Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-picklist-component[@cx-prop-label=&apos;Salutation&apos;]//lyte-icon[@class=&apos;dropdown&apos;].
        /// </summary>
        internal static string SalutationDrpdwn {
            get {
                return ResourceManager.GetString("SalutationDrpdwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[text()=&apos;java&apos;].
        /// </summary>
        internal static string SkillSet {
            get {
                return ResourceManager.GetString("SkillSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;addSkills&apos;].
        /// </summary>
        internal static string SkillSetDrpDwn {
            get {
                return ResourceManager.GetString("SkillSetDrpDwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(text(),&apos;Karnataka Health Institute, Gokak, Belgaum, Karnataka, India - 591306&apos;)].
        /// </summary>
        internal static string State_Province {
            get {
                return ResourceManager.GetString("State_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-text-component[@cx-prop-label=&apos;State/Province&apos;].
        /// </summary>
        internal static string State_ProvinceDrpDwn {
            get {
                return ResourceManager.GetString("State_ProvinceDrpDwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;cruxErrMsg cruxErrorMsgDesc &apos;].
        /// </summary>
        internal static string SubmitApplicationError {
            get {
                return ResourceManager.GetString("SubmitApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@type=&apos;submit&apos;].
        /// </summary>
        internal static string SubmitBtn {
            get {
                return ResourceManager.GetString("SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //crux-text-component[@cx-prop-label=&apos;Why Join Numadic ?&apos;].
        /// </summary>
        internal static string WhyJoinNumadic {
            get {
                return ResourceManager.GetString("WhyJoinNumadic", resourceCulture);
            }
        }
    }
}
